### ISSUE TITLE
RSpecでのテスト環境の構築

### ISSUE THREAD

**Issue by garammasala29** [atsushimemet/vook_web_v3#14]
## 目的
不具合やバグを見つけ、コードの品質向上のためテストを書く
## 今後書いていくスペック
- モデルスペック
自分でmodelに作ったメソッドに対して最低一つ正常系のスペックを書く
- システムスペック
CRUDそれぞれに対して最低一つ正常系のスペックを書く
  - [x] Magazineのシステムスペックがまだなので作成 

## 本issueで対応しておくところ
- [x] エラーメッセージを出現させる
- [x] フラッシュメッセージを出現させる

**Comment by atsushimemet** [comment]
@garammasala29 
ざっとコメントです。

# システムスペックのテストの進め方について
システムスペックのテストは、実現したいユーザー体験が実現できているか、というテストだと理解しているので、以下1〜3を実現できるといいのかなと思ってます。

1.開発側で実現したいユーザー体験の確認するためにシステムスペックを書きテスト
2. 要求持つ側(ここではたまりさん)の実現したいユーザー体験のヒアリング ＊デプロイ後
3. 2のシステムスペックを書きテスト

# テスト品質向上について
また品質高めようとすると、異常系も当然書く必要があるし、コントローラー、ビュー、ヘルパー、ジョブあたりのスペックも書く必要あるということなのだと理解してます。PJの推進具合をみて、どこかのタイミングで書きましょう。おって相談させてください。

# CICDについて
今回書くミニマムなテストに対して、自動化されているといいと思いました。ソースやテストが多くなる前に作れてる方が後々らくかも。

個人的なスキルセットで恐縮なんだけど、cicd検討する際はgithub actionsだと楽です。
