### ISSUE TITLE
「Search The Vintage」を「Discovery」に、「Vook Magazine」を「Magazine」にリネーム

### ISSUE THREAD

**Issue by garammasala29** [atsushimemet/vook_web_v3#47]
# Issue
先日の打ち合わせにて決定
トップページと各ページの帯修正
一緒にclass名も変更しておく

**Comment by atsushimemet** [comment]
@garammasala29 
DiscoverはDiscoveryだと思う!
全部名詞で揃えるイメージ。

あと、たまりさんの認識もdiscovery
https://vook-co.slack.com/archives/C04P4S8BZKP/p1687782968203329?thread_ts=1687576257.238649&cid=C04P4S8BZKP
