### ISSUE TITLE
RailsアプリをAWSにデプロイ

### ISSUE THREAD

**Issue by garammasala29** [atsushimemet/vook_web_v3#5]
AWSにてEC2+RDSのRails環境構築

1. VPCでネットワークを構築
2. EC2でWebサーバーを構築
3. RDSでDBサーバーを構築
4. EC2にRailsを導入 
6. RDSとRailsを接続
7. Route53でドメイン登録

**Comment by atsushimemet** [comment]
@garammasala29 
ここは、古賀のアカウントでやる&協業する想定だったけど認識合ってる?

**Comment by garammasala29** [comment]
@atsushimemet 
自分もAWSの勉強してたのと不要なドメインもあったのでお試しデプロイしてみようと思ってた。
Railsだとどうなるのか、ここに作業ログを残してデプロイしてみて、それを元に本番に反映させるイメージ。
どうですか？

**Comment by garammasala29** [comment]
# 1.VPCでネットワークを構築
## VPCを作成
<img width="621" alt="image" src="https://user-images.githubusercontent.com/69446373/229995708-267a8b5a-907a-44df-b56f-f62beb2ac9a0.png">

- 名前タグ：vook-rails-vpc
- IPv4 CIDR：10.0.0.0/16 （VPCのIPアドレスの範囲）

## サブネットを作成
### パブリックサブネット
<img width="618" alt="image" src="https://user-images.githubusercontent.com/69446373/229996152-7856b38d-3a39-427d-af5f-4766a5ec62f6.png">

- サブネット名：vook-rails-public-subnet-1a
- アベイラビリティーゾーン：ap-northeast-1a
- IPv4 CIDR：10.0.10.0/24（VPC内のIPアドレス）

### プライベートサブネット
<img width="622" alt="image" src="https://user-images.githubusercontent.com/69446373/229999383-62c5b218-4df0-4501-989f-571e14b227b1.png">

- サブネット名：vook-rails-private-subnet-1a
- アベイラビリティーゾーン：ap-northeast-1a
- IPv4 CIDR：10.0.20.0/24（VPC内のIPアドレス）

## ルーティングの設定
パブリックサブネットからインターネットに接続できるようにする
0.0.0.0/0(10.0.0.0/16以外)はインターネットゲートウェイに接続するよう設定する

### インターネットゲートウェイを作成しVPCにアタッチ
<img width="627" alt="image" src="https://user-images.githubusercontent.com/69446373/230000915-7af0ff28-9e18-487f-b4a4-d25000498288.png">
<img width="775" alt="image" src="https://user-images.githubusercontent.com/69446373/230001174-dc496b2f-81b5-48d7-b065-abf5127933d2.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/69446373/230001220-a4c6b03e-f07d-415c-ab4c-1ed3a7cf8344.png">

- 名前タグ：vook-rails-igw

### パブリックサブネット用のルートテーブルの設定
<img width="932" alt="image" src="https://user-images.githubusercontent.com/69446373/230002645-df3c63b2-dc7e-470e-86a5-d400c78e4adb.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/69446373/230002858-84205b05-b967-4124-8dc1-e65798859e23.png">

### プライベートサブネット用のルートテーブルの設定
<img width="623" alt="image" src="https://user-images.githubusercontent.com/69446373/230003977-5a932273-b5d0-46b4-8971-16c036f27d12.png">

- 名前タグ vook-rails-private-route
<img width="971" alt="image" src="https://user-images.githubusercontent.com/69446373/230004389-4b002acc-dd1b-468c-acec-02464d304243.png">
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/69446373/230004471-2628966e-0236-40a6-8763-34524ca1cf74.png">

**Comment by garammasala29** [comment]
# 2.EC2でWebサーバーを構築
## EC2を作成
![image](https://user-images.githubusercontent.com/69446373/230036356-60d6c42b-624d-4c1a-9ba7-35d52ad220fc.png)
##### Name and tags
- Name: vook-rails-web
##### AMI(Amazon Machine Image、サーバーのテンプレ)を選択
- 今回はAmazon Linux2
##### インスタンスタイプ(サーバースペック)の選択
- 今回はt2.micro
##### キーペア (ログイン)
- 新規作成(vook-rails-ssh-key)
##### ネットワーク設定
- VPC、パブリックサブネットを選択
- セキュリティグループ(vook-rails-web)
- セキュリティグループルールを設定。
  - SSH
  - HTTP `0.0.0.0/0`と`::/0`
  - 本来ここでHTTPSも？
##### ストレージの追加
- 今回は1x8GiBgp2
## Elastic IPの作成
再起動によって動的に変わってしまうパブリックIPアドレスを固定する
<img width="632" alt="image" src="https://user-images.githubusercontent.com/69446373/230039901-1bb040fc-0c47-4931-981a-6e63122b0a1b.png">
<img width="625" alt="image" src="https://user-images.githubusercontent.com/69446373/230040774-e22ad8ab-5ac0-4b20-8fef-9d5345c873ac.png">
- インスタンス、vook-rails-webを選択

## パブリックアドレスでSSH接続できるか確認
```
$chmod 600 ~/Downloads/vook-rails-ssh-key.pem 
$ssh -i ~/Downloads/vook-rails-ssh-key.pem ec2-user@52.199.105.145

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
8 package(s) needed for security, out of 9 available
Run "sudo yum update" to apply all updates.
```

**Comment by garammasala29** [comment]
# 3.RDSでDBサーバーを構築
## セキュリティグループを修正
インバウンドルールを追加
<img width="865" alt="image" src="https://user-images.githubusercontent.com/69446373/230104950-acb56262-e7cc-464a-a181-3de117a7115d.png">

- MYSQL/Auroraとソースにvook-rails-webのセキュリティグループを追加
## サブネットとサブネットグループを追加
マルチAZが推奨されており、もうひとつアベイラビリティゾーンを作って構築する必要がある。
##### VPC>サブネットを追加
<img width="619" alt="image" src="https://user-images.githubusercontent.com/69446373/230237004-6a771d16-dcc0-499a-8356-65806d6f24f3.png">

- サブネット名：vook-rails-private-subnet-1c
- アベイラビリティーゾーン：ap-northeast-1c
- IPv4 CIDR：10.0.21.0/24
##### RDS>DB サブネットグループを作成
<img width="530" alt="image" src="https://user-images.githubusercontent.com/69446373/230237238-481160bf-d407-49db-8808-8b38b83727f0.png">

- グループ名：vook-rails-subnet-group
- VPCを選択
- 1aのアベイラビリティでプライベートのCIDR`10.0.20.0/24`を選択
## RDSでDBの作成
![image](https://user-images.githubusercontent.com/69446373/230238291-ccd2e795-34c3-46e2-9734-5aa4722a4308.png)

##### エンジン
- 指定があったのでMySQL、バージョンは最新の8.0.32
##### テンプレ
- 今回は開発/テスト
##### マルチAZについて
- せっかくアベイラビリティゾーンを作ったが今回は単一DBインスタンスに設定。本番では必要なものを選択
##### 設定
- 識別子：vook-rails-db
- ユーザー名：root
- パスワード名：password
##### インスタンスサイズ
- 今回はパースと可能クラス>db.t2.micro（以前の世代クラス）
##### ストレージ
- 今回は汎用SSD(gp2)、20GB、自動スケーリング無効
##### 接続
- VPC、サブネットグループ、セキュリティグループ、アベイラビリティは任意のもの
- パブリックアクセスなし
##### モニタリング
- テスト環境なので今回はなし

**Comment by garammasala29** [comment]
# 4.EC2にRailsを導入
## EC2の環境構築
```
ssh -i ~/.ssh/vook-rails-ssh-key.pem ec2-user@52.199.105.145
# 既存のプログラムアップデート
sudo yum -y update

# ここでセキュリティ対策のためec2-userは削除しtestというユーザーを作成、パスワードも変更
# サーバにSSHログインできるよう、鍵の設定もしておく

# 環境構築に必要なパッケージをインストール
sudo yum  -y install git make gcc-c++ patch libyaml-devel libffi-devel libicu-devel zlib-devel readline-devel libxml2-devel libxslt-devel ImageMagick ImageMagick-devel openssl-devel libcurl libcurl-devel curl wget

# rbenv(rubyのバージョン管理ツール)をインストール、パスを通す
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
source .bash_profile

# ruby-build(Rubyをバージョンごとにビルドするツール)のインストール
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
rbenv rehash

# rubyのインストール
rbenv install 3.2.2
rbenv global 3.2.2
rbenv rehash

# nvm(node.js管理ツール)のインストール
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
source ~/.bashrc

# nodeのインストール(偶数が安定版)
~nvm install 18.15.0~
最新のnodeがサポートできるglibcが搭載されていないので、nodeのバージョンを下げる
nvm install 16.20.0

# yarn(JSパッケージマネージャ)をインストール
npm install -g yarn

# MariaDBのアンインストール
yum list installed | grep mariadb
sudo yum remove mariadb-libs.x86_64

# MySQL8.0のリポジトリ追加(https://dev.mysql.com/downloads/repo/yum/で選択した)
sudo yum localinstall -y https://dev.mysql.com/get/mysql80-community-release-el7-7.noarch.rpm

# MySQL8.0リポジトリの有効可
sudo yum-config-manager --disable mysql57-community
sudo yum-config-manager --enable mysql80-community

# クライアントツールのインストール
sudo yum install -y mysql-community-client mysql-devel
```
## Nginx(Webサーバー)のインストール
Webサーバーには複数種類があるが、Railsは一般的にNginxと相性がよいとされる。
(Nginxが軽量で高速な反応をすることができ、多くのリクエストを処理することができるため)
```
# Amazon Linux2にはnginxのyumがないのでAmazon Linux Extraを追加しインストール
sudo amazon-linux-extras install nginx1
```
`/etc/nginx/nginx.conf`のhttp部分を書き換える
```
http {
    ~~~~~~
-   server {
-      ~~~~~~~
-    }

+   gzip on;
+   gzip_http_version 1.0;
+   gzip_proxied any;
+   gzip_min_length 500;
+   gzip_disable "MSIE [1-6]\.";
+   gzip_types text/plain text/xml text/css
               text/comma-separated-values
               text/javascript application/x-javascript
               application/atom+xml;
}
```
`/etc/nginx/conf.d/test.conf`を作成
```
upstream puma {
  server unix:/var/www/test_app/tmp/sockets/puma.sock;
}

server {
  server_name  test.com;

  keepalive_timeout 0;

  access_log  /var/log/nginx/test.access.log  main;
  client_max_body_size 4G;

  root /var/www/test/public;
  location ~ .*\.(swf|SWF|ico|ICO|jar|txt|gz|js) {
    root /var/www/test/public;
    expires 15m;
    break;
  }
  location ~ ^\/fonts\/* {
    root /var/www/test/public;
    expires 15m;
    break;
  }
  location ~ ^\/assets\/* {
    root /var/www/test/public;
    break;
  }
  location ~ ^\/favicon\/* {
    root /var/www/test/public;
    break;
  }
  location = /manifest.json {
    root /var/www/test/public;
    break;
  }
  location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;

    #auth_basic "Restricted";
    #auth_basic_user_file /etc/nginx/.htpasswd;
    #if ($http_x_forwarded_proto = "http") {
     #rewrite ^(.*) https://$server_name$1
      #break;
    #}
    proxy_pass http://puma;
  }
}
```

## Githubと連携しclone
`/var/www/アプリ名`というディレクトリ構造にするのが通例。vookもそこにインストール
```
sudo chown test:test /var
mkdir /var/www

[test@ip-10-0-10-4 .ssh]$ ssh-keygen -t rsa
cat id_rsa.pub
```
で公開鍵をコピーし、https://github.com/settings/keysで登録
.ssh/configファイルを
```
Host github
  Hostname github.com
  User git
  IdentityFile ~/.ssh/id_rsa
```
と設定し`ssh -T github`コマンドでログインする
```
[test@ip-10-0-10-4 www]$ git clone git@github.com:atsushimemet/vook_web_v3.git
```

**Comment by garammasala29** [comment]
# 5.RDSとRailsを接続
wip

**Comment by garammasala29** [comment]
# 6.Route53でドメイン登録
wip

**Comment by atsushimemet** [comment]
@garammasala29 
アクセスするとbad gatewayで弾かれるが、これは想定通り？

**Comment by garammasala29** [comment]
@atsushimemet 
#7 の通り、確認できたので今はサーバー停止させてます。必要あれば立ち上げます〜

**Comment by atsushimemet** [comment]
@garammasala29 
一瞬立ち上げてもらえると嬉しい！webで確認させてもらいたいです。

**Comment by garammasala29** [comment]
@atsushimemet 
それでは確認よろしくお願いします！
http://aws-and-infra.pw/

**Comment by atsushimemet** [comment]
@garammasala29 
確認できました！停止してもらってOKです！

**Comment by garammasala29** [comment]
# Elastic IPアドレスでアドレス固定
EC2のElastic IP アドレスから新しいIPアドレスを確保
EC2に紐づける
<img width="1021" alt="image" src="https://github.com/atsushimemet/vook_web_v3/assets/69446373/5adc81e9-7a1f-424f-ac4a-07e43a960347">
