### ISSUE TITLE
バグレポート: OGP画像が表示されない

### ISSUE THREAD

**Issue by garammasala29** [atsushimemet/vook_web_v3#56]
# 再現手順
本番環境の画像をおいたにも関わらず、共有時にOGP画像が表示されない。
https://ogp.buta3.net/ で確認

# 期待される振る舞い
表示されるようになる

# スクショ
![image](https://github.com/atsushimemet/vook_web_v3/assets/69446373/43399527-ff4e-4892-bacf-dcf303370964)

# 環境
## ブラウザ
# 関連イシュー

**Comment by atsushimemet** [comment]
メインOGP画像が反映されていない
