### ISSUE TITLE
ヘッダーの順番をユーザー導線に従った形に変更するのはどうか

### ISSUE THREAD

**Issue by atsushimemet** [atsushimemet/vook_web_v3#67]
# 提案
- 現状: About, Search, Magazine, Instagram, Tiktok
- 提案: Instagram, Tiktok, Knowledge, Magazine, Discovery, Community, About

# 背景
- ユーザー導線に沿った形でヘッダーがあるといいのでは、と感じた

**Comment by atsushimemet** [comment]
0. Instagram
0. Tiktok
1. Knowledge
2. Magazine
3. Discovery
4. Community
9. About

**Comment by garammasala29** [comment]
about > knowledge > magazine > discovery > community > insta icon > tikitok icon > login
正規の色付き仕様
